import os
import sys
sys.path.append(os.getcwd())
from pathinit import EVIDIST_ROOT_PATH
import panel as pn
import param
from tkinter import Tk, filedialog
from styles import custom_style
from actions import gen_xf_mappings, DataOperatorPlus
import pickle
import json
import io
import zipfile


class pgPlusLoadSession(param.Parameterized):

    ready = param.Boolean(default=False)

    @param.output('input_file_names', 'output_file_names', 'configs')
    def output(self):
        # self.file_names = {'dss_main' : self.filename_texts[0].value}
        return self.input_file_names, self.output_file_names, self.configs

    def __init__(self):
        super().__init__()

        self.info_texts = [pn.pane.Markdown("""<b style='font-size:12pt'>Please select the Plus session (*.zip) file:</b>
                                               <br>This file contains simulation configuration information and results, generated by saving a session on the display results page.</br>""",
                                            width=400)
                           ]

        self.file_browse_buttons = [pn.widgets.Button(name='Browse', align=('center','center'), button_type='success', width=100)]

        self.filename_texts = [pn.widgets.StaticText(value="Selected File: ", align=('center','center'))]

        self.file_browse_buttons[0].on_click(lambda event, button_index=0: self.select_files(button_index, event))

        self.progress_bar = pn.widgets.Progress(name='Progress', value=0, width=500, align=('center','center'))
        self.saved_session_file_name = ""
        self.input_file_names = param.Dict()
        self.output_file_names = param.Dict()
        self.configs = param.Dict()

        self.progress_start_button = pn.widgets.Button(name='Upload selected files', button_type='primary', align=('center','center'))
        self.progress_start_button.on_click(self.upload_on_click)

        # External callback function
        self.external_callback = None

    def panel(self):

        return pn.Column(
            pn.Row(self.info_texts[0], pn.Spacer(width=20), self.file_browse_buttons[0], self.filename_texts[0]),
            pn.Row(self.progress_bar, self.progress_start_button)
        )

    def select_files(self, button_index, event):
        root = Tk()
        root.withdraw()
        root.call('wm', 'attributes', '.', '-topmost', True)
        initial_dir_path = EVIDIST_ROOT_PATH + "/data/saved_sessions_plus"
        file_name = filedialog.askopenfilename(multiple=False, initialdir=initial_dir_path)
        if file_name == "":
            file_name = "Selected File: "
        self.filename_texts[button_index].value = file_name
        return file_name

    def upload_on_click(self,event):
        file_name_check = True
        for fn in self.filename_texts:
            print(fn.value)
            if fn.value == 'Selected File: ':
                print('No pass!')
                pn.state.notifications.warning('Some input files are not selected!', duration=4000)
                file_name_check = False
                break

        if file_name_check:
            try:
                self.progress_bar.value = 10
                self.unzip_and_save(self.filename_texts[0].value)
                self.ready = True
                self.progress_bar.value = 100
                pn.state.notifications.success('Files successfully uploaded!', duration=4000)

            except Exception:
                pn.state.notifications.error('Files not found! Make sure file paths are correct.', duration=4000)

    def unzip_and_save(self, zip_filepath):
        """Unzips the contents of a zip file, handling JSON and CSV files differently.
        """

        temp_directory = EVIDIST_ROOT_PATH + "/data/temp_sim_plus/"

        # Open the zip file in binary read mode ("rb")
        with open(zip_filepath, "rb") as f:
            zip_data = f.read() # Read the contents of the file into memory

        with zipfile.ZipFile(io.BytesIO(zip_data)) as zf:
            for file_info in zf.infolist():
                if not file_info.is_dir():
                    filename = file_info.filename
                    file_data = zf.read(filename)

                    if filename.endswith(".json"):
                        json_data = json.loads(file_data)
                        # json_data["configs"]["month"] = int(json_data["configs"]["month"])

                        self.input_file_names = json_data["input_file_names"]
                        self.configs = json_data["configs"]
                        self.output_file_names = json_data["output_file_names"]
                    elif filename.endswith(".csv"):
                        # Save CSV files to the target directory
                        file_path = os.path.join(temp_directory, filename)
                        os.makedirs(os.path.dirname(file_path), exist_ok=True)
                        with open(file_path, "wb") as f:
                            f.write(file_data)
                    elif filename.endswith(".pickle"):
                        pn.state.dop = pickle.loads(file_data)
                    else:
                        print(f"Unsupported file type: {filename}")  # Optional